// <auto-generated />
namespace KSTVideo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removeQuantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeQuantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202105052352524_removeQuantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
